"""add subscriptions table

Revision ID: a2a515190fb1
Revises: 
Create Date: 2025-07-03 16:08:10.601710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a515190fb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('subscribed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscribed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
